title: Marcelo KALONJI
logo: /assets/img/Kim2.png
description: <style> img[src*='Kim2'] { border-radius: 50%; width: 150px; height: 150px; object-fit: cover; } </style>
show_download: true
theme: jekyll-theme-minimal
